language: c

env:
  global:
    - RACKET_DIR=~/racket
  matrix:
    - RACKET_VERSION=HEAD  PACKAGE=alexis-util
    - RACKET_VERSION=HEAD  PACKAGE=alexis-multicast

before_install:
  - git clone https://github.com/greghendershott/travis-racket.git
  - cat travis-racket/install-racket.sh | bash
  - export PATH="${RACKET_DIR}/bin:${PATH}"

install:
  - raco pkg install --deps search-auto --link $TRAVIS_BUILD_DIR/$PACKAGE
  - raco pkg install --deps search-auto cover cover-coveralls

script:
  - raco test -xp $PACKAGE
  - raco cover -f coveralls -d $TRAVIS_BUILD_DIR/coverage -p $PACKAGE
